/**
 * Application Configuration
 * This file is auto-generated from environment variables by build-config.js
 * DO NOT EDIT THIS FILE DIRECTLY - edit .env or set environment variables instead
 * 
 * To regenerate: npm run build
 */

const CONFIG = {
    // Toggle AI recommendations on/off
    ENABLE_AI_RECOMMENDATIONS: true,
    
    // OpenRouter API Key (from environment variable)
    // This will be replaced by build-config.js
    OPENROUTER_API_KEY: '',
    
    // Available Models
    MODELS: [
        {
            id: 'meta-llama/llama-4-maverick',
            name: 'Llama 4 Maverick (Groq)',
            context: '128K',
            description: 'Super rapid via Groq infrastructure'
           
        },
        {
            id: 'x-ai/grok-4.1-fast',
            name: 'Grok 4.1 Fast',
            context: '2M',
            description: 'Fast and powerful model',
            isDefault: true
        },
        {
            id: 'google/gemini-3-pro-preview',
            name: 'Gemini 3 Pro Preview',
            context: '1M',
            description: 'Large context window'
        }
    ],
    
    // Get default model
    getDefaultModel() {
        return this.MODELS.find(m => m.isDefault) || this.MODELS[0];
    }
};

window.APP_CONFIG = CONFIG;
