/**
 * Build script to generate config.js from environment variables
 * This prevents API keys from being committed to git
 * 
 * Usage:
 *   node build-config.js
 * 
 * For Vercel: This runs automatically during build
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env file (for local development)
if (fs.existsSync('.env')) {
    require('dotenv').config();
}

// Get API key from environment variable
const apiKey = process.env.OPENROUTER_API_KEY || '';
const enableAI = process.env.ENABLE_AI_RECOMMENDATIONS !== 'false';

if (!apiKey) {
    console.warn('⚠️  WARNING: OPENROUTER_API_KEY not found in environment variables');
    console.warn('   Create a .env file with OPENROUTER_API_KEY=your-key-here');
    console.warn('   Or set it as an environment variable');
}

// Generate config.js content
const configContent = `/**
 * Application Configuration
 * This file is auto-generated from environment variables by build-config.js
 * DO NOT EDIT THIS FILE DIRECTLY - edit .env or set environment variables instead
 */

const CONFIG = {
    // Toggle AI recommendations on/off
    ENABLE_AI_RECOMMENDATIONS: ${enableAI},
    
    // OpenRouter API Key (from environment variable)
    OPENROUTER_API_KEY: '${apiKey}',
    
    // Available Models
    MODELS: [
        {
            id: 'meta-llama/llama-4-maverick',
            name: 'Llama 4 Maverick (Groq)',
            context: '128K',
            description: 'Super rapid via Groq infrastructure'
           
        },
        {
            id: 'x-ai/grok-4.1-fast',
            name: 'Grok 4.1 Fast',
            context: '2M',
            description: 'Fast and powerful model',
            isDefault: true
        },
        {
            id: 'google/gemini-3-pro-preview',
            name: 'Gemini 3 Pro Preview',
            context: '1M',
            description: 'Large context window'
        }
    ],
    
    // Get default model
    getDefaultModel() {
        return this.MODELS.find(m => m.isDefault) || this.MODELS[0];
    }
};

window.APP_CONFIG = CONFIG;
`;

// Write config.js
const configPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Generated js/config.js from environment variables');
if (apiKey) {
    console.log(`   API Key: ${apiKey.substring(0, 10)}...${apiKey.substring(apiKey.length - 4)}`);
} else {
    console.log('   ⚠️  No API key found - using empty string');
}

